// src/components/CenterOrLeft.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { useHtmlToCanvas } from '@/use/htmlToCanvas'
import { createFilename, blurOnEnter } from '@/use/helper'

const props = defineProps<{
	isLeft?: boolean
}>()

const { state } = useHtmlToCanvas()

const headline = ref(props.isLeft ? 'Bauchbinde links' : 'Bauchbinde zentriert')
const subtitle = ref(props.isLeft ? 'www.website.tld' : 'Untertitel')

const filename = computed(() => createFilename(headline.value))
</script>

<template>
	<a
		:href="state.imageSrc"
		:download="filename"
		id="download-link"
		class="relative mx-auto block max-w-full"
		:class="{ '!hidden': !state.isGenerated }"
	>
		<img class="mx-auto block max-w-full" :src="state.imageSrc" alt="" />
	</a>

	<section
		id="canvas"
		class="lower-third mx-auto flex flex-col justify-end"
		:class="[isLeft ? 'items-baseline' : 'items-center', { '!hidden': state.isGenerated }]"
	>
		<div class="headline text-peach relative z-10 font-semibold">
			<input
				v-model="headline"
				type="text"
				class="input is-stretchy bg-transparent px-1 font-semibold"
				:class="{ '!hidden': state.isPainting }"
				@keyup.enter="blurOnEnter"
			/>
			<div
				class="text h2c-offset px-1"
				:class="{ 'text-center': !isLeft, '!hidden': !state.isPainting }"
				style="--h2c-offset: -22px"
			>
				{{ headline }}
			</div>
		</div>
		<div class="subtitle text-chocolate relative z-20 font-medium">
			<input
				v-model="subtitle"
				type="text"
				class="input is-stretchy bg-transparent px-1 font-medium"
				:class="{ '!hidden': state.isPainting }"
				@keyup.enter="blurOnEnter"
			/>
			<div
				class="text h2c-offset px-1"
				:class="{ 'text-center': !isLeft, '!hidden': !state.isPainting }"
				style="--h2c-offset: -15px"
			>
				{{ subtitle }}
			</div>
		</div>
	</section>
</template>

<style>
.route-center .headline {
	max-width: 181.2em;
}

.route-center .headline .input {
	/* width: calc(100vw - 8.5rem); */
	max-width: 106.5rem;
}

.route-left .headline {
	margin-inline: 7.8em;
	padding-inline: 3.6em;
}

.route-left .headline .input {
	/* width: calc(100vw - 14.75rem); */
	max-width: 105.25rem;
}

.route-center .subtitle {
	max-width: 169.8em;
}

.route-center .subtitle .input {
	/* width: calc(100vw - 8.5rem); */
	max-width: 99.125rem;
}

.route-left .subtitle {
	margin-inline: 9em;
	padding-inline: 2.2em;
}

.route-left .subtitle .input {
	/* width: calc(100vw - 14.5rem); */
	max-width: 105.5rem;
}
</style>

// src/routes/CenterOrLeft.svelte
<script>
// export let location
export let isLeft = false
export let imageGenerated = false
export let src = ''

let headline = isLeft ? 'Bauchbinde links' : 'Bauchbinde zentriert'
let headlineInput
let subtitle = isLeft ? 'www.website.tld' : 'Untertitel'
let subtitleInput

$: filename = headline.trim().replace(/[^a-z0-9\-\s]/gi, '').substr(0, 16).trim() + '.png'

const hideAllInputs = () => {
	headlineInput.blur()
	subtitleInput.blur()
}

const onKeyPress = e => {
	if (e.charCode === 13) {
		hideAllInputs()
	}
}
</script>

<a href={src} download={filename} id="download-link" class="relative block mx-auto max-w-full" class:hidden={!imageGenerated}>
	<img class="block mx-auto max-w-full" {src} alt="">
</a>

<section id="canvas" class="lower-third mx-auto flex flex-col justify-end" class:items-center={!isLeft} class:items-baseline={isLeft} class:hidden={imageGenerated} on:click={hideAllInputs}>
	<div class="headline text-peach font-semibold relative z-10">
		<input type="text" class="stretchy h2c-font-offset-3 px-1 bg-transparent font-semibold" class:text-center={!isLeft} on:click|stopPropagation on:keypress={onKeyPress} bind:this={headlineInput} bind:value={headline}>
	</div>

	<div class="subtitle text-chocolate font-medium relative z-20">
		<input type="text" class="stretchy h2c-font-offset-3 px-1 bg-transparent font-medium" class:text-center={!isLeft} on:click|stopPropagation on:keypress={onKeyPress} bind:this={subtitleInput} bind:value={subtitle}>
	</div>
</section>

<style>
.lower-third.items-center .headline {
	max-width: 181.2em;
}

.lower-third.items-center .headline input {
	width: calc(100vw - 8.5rem);
	max-width: 106.5rem;
}

.lower-third.items-baseline .headline {
	margin-left: 7.8em;
	margin-right: 7.8em;
	padding-left: 3.6em;
	padding-right: 3.6em;
}

.lower-third.items-baseline .headline input {
	width: calc(100vw - 14.75rem);
	max-width: 105.25rem;
}

.lower-third.items-center .subtitle {
	max-width: 169.8em;
}

.lower-third.items-center .subtitle input {
	width: calc(100vw - 8.5rem);
	max-width: 99.125rem;
}

.lower-third.items-baseline .subtitle {
	margin-left: 9em;
	margin-right: 9em;
	padding-left: 2.2em;
	padding-right: 2.2em;
}

.lower-third.items-baseline .subtitle input {
	width: calc(100vw - 14.5rem);
	max-width: 105.5rem;
}
</style>
