// src/App.vue
<script setup lang="ts">
import { useHtmlToCanvas } from '@/use/htmlToCanvas'

const { state, generateImage } = useHtmlToCanvas()
</script>

<template>
	<header id="navbar" class="fixed left-0 top-0 z-40 w-full" :class="{ 'opacity-30': state.isPainting }">
		<nav
			class="flex justify-center gap-x-5 border-t-4 border-[--pink] bg-white py-4 pb-5 font-medium text-[--gray-900]"
			:class="{ 'pointer-events-none': state.isPainting }"
		>
			<RouterLink to="/">Bauchbinde</RouterLink>
			<RouterLink to="/left">Bauchbinde links</RouterLink>
			<RouterLink to="/center-qr">Bauchbinde mit QR-Code</RouterLink>
			<RouterLink to="/block-left">Textblock links</RouterLink>
			<RouterLink to="/block-right">Textblock rechts</RouterLink>
		</nav>
		<a
			href="https://github.com/cniklas/tmt-image-generator"
			class="absolute right-4 top-5 size-6 rounded-xl"
			aria-label="GitHub repo"
			rel="noopener"
		>
			<svg aria-hidden="true" class="size-6 fill-current" viewBox="0 0 16 16" width="24" height="24">
				<path
					fill-rule="evenodd"
					d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z"
				/>
			</svg>
		</a>

		<button
			type="button"
			aria-label="Bild generieren"
			id="camera-button"
			:class="{ '!hidden': state.isGenerated }"
			@click="generateImage"
		>
			<svg
				aria-hidden="true"
				class="size-8 fill-current"
				fill="#ffffff"
				viewBox="0 0 24 24"
				width="32"
				height="32"
				xmlns="http://www.w3.org/2000/svg"
			>
				<circle cx="12" cy="12" r="3.2"></circle>
				<path
					d="M9 2L7.17 4H4c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2h-3.17L15 2H9zm3 15c-2.76 0-5-2.24-5-5s2.24-5 5-5 5 2.24 5 5-2.24 5-5 5z"
				/>
				<path d="M0 0h24v24H0z" fill="none" />
			</svg>
		</button>
	</header>

	<main class="mt-16" :class="`route-${String($route.name)}`">
		<RouterView />
	</main>
</template>

// src/App.svelte
<script>
import TailwindCSS from './components/TailwindCSS.svelte'

import { Router, Link, Route } from 'svelte-routing'
export let url = ''
import CenterOrLeft from './routes/CenterOrLeft.svelte'
import CenterQR from './routes/CenterQR.svelte'
import GoldenRatio from './routes/GoldenRatio.svelte'


import html2canvas from 'html2canvas'

let imageGenerated = false
let isPainting = false
let src = ''
let navbar

const generate = async () => {
	if (!isPainting) {
		isPainting = true
		window.scroll(0, 0);

		try {
			// `useCORS: true` wird für die QR-Code-API benötigt
			const canvas = await html2canvas(document.querySelector('#canvas'), {backgroundColor: null, useCORS: true, logging: true})
			imageGenerated = true
			src = canvas.toDataURL('image/png')
		} catch(error) {
			console.error(error)
		} finally {
			isPainting = false
		}
	}
}

const resetPage = () => {
	imageGenerated = false
	isPainting = false
	src = ''

	window.scroll(0, 0)
	navbar.focus()
}
</script>

<TailwindCSS />

<Router url="{url}">
	<div id="navbar" bind:this={navbar} class="fixed top-0 left-0 w-full z-40" class:opacity-30={isPainting}>
		<nav class="flex justify-center py-4 pb-5 font-medium text-gray-900 bg-white border-t-4 border-pink-600" class:pointer-events-none={isPainting}>
			<Link to="/" on:click={resetPage}>Bauchbinde</Link>
			<Link to="center-qr" on:click={resetPage}>Bauchbinde mit QR-Code</Link>
			<Link to="left" on:click={resetPage}>Bauchbinde, links</Link>
			<Link to="block" on:click={resetPage}>Textblock</Link>
			<Link to="block-right" on:click={resetPage}>Textblock, rechts</Link>
		</nav>

		<button id="camera-button" class="absolute top-20 left-1/2 -translate-x-2/4 p-2 flex justify-center items-center cursor-pointer bg-gray-900 hover:bg-gray-800 text-white border-4 border-current rounded-full focus:outline-none" class:hidden={imageGenerated} on:click={generate}>
			<svg class="fill-current w-8" fill="#ffffff" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
				<circle cx="12" cy="12" r="3.2"/>
				<path d="M9 2L7.17 4H4c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2h-3.17L15 2H9zm3 15c-2.76 0-5-2.24-5-5s2.24-5 5-5 5 2.24 5 5-2.24 5-5 5z"/>
				<path d="M0 0h24v24H0z" fill="none"/>
			</svg>
		</button>
	</div>

	<main class="mt-16">
		<Route path="/"><CenterOrLeft {src} {imageGenerated} /></Route>
		<Route path="center-qr" component="{CenterQR}" {src} {imageGenerated} />
		<Route path="left" component="{CenterOrLeft}" isLeft {src} {imageGenerated} />
		<Route path="block" component="{GoldenRatio}" {src} {imageGenerated} />
		<Route path="block-right" component="{GoldenRatio}" isFlipped {src} {imageGenerated} />
	</main>
</Router>

<style global>
:root {
	--btn-box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 1px 5px 0 rgba(0,0,0,0.12), 0 3px 1px -2px rgba(0,0,0,0.2);
}

@media (min-width: 1920px) {
	body {
		overflow-x: hidden;
	}
}

button {
	cursor: pointer;
}

.is-editable {
	cursor: pointer;
}

.is-editable.editing {
	cursor: initial;
}

.h2c-font-offset--3 {
	transform: translateY(-3px);
}

.h2c-font-offset-3 {
	transform: translateY(3px);
}

.h2c-font-offset-4 {
	transform: translateY(4px);
}

nav a {
	margin: 0 .625rem;
}

nav a[aria-current=page] {
	@apply text-pink-600;
}

#navbar {
	transition: opacity 300ms ease-in-out;
}

#camera-button {
	box-shadow: var(--btn-box-shadow);
	transform: translateX(var(--tw-translate-x));
	transition: background-color 200ms cubic-bezier(0.4,0,0.6,1), transform 144ms ease-out;
}

#camera-button:hover,
#camera-button:focus {
	transform: translateX(var(--tw-translate-x)) scale(1.1);
}

#download-link {
	width: 1920px;
}

#download-link::after {
	@apply absolute top-4 left-1/2 py-2.5 px-4 font-medium text-lg tracking-wide bg-gray-800 text-white border-4 border-current rounded-full;
	content: 'Bild speichern';
	transform: translateX(-50%);
	box-shadow: var(--btn-box-shadow);
}

#canvas {
	font-family: 'Poppins', sans-serif;
	/* 10px als font-base */
	font-size: .625rem;
	line-height: 1;

	height: 1080px;
	width: 1920px;
}

.lower-third .headline {
	padding: 1.1em 0;
}

.lower-third.items-center .headline {
	padding-left: 5em;
	padding-right: 5em;
}

.lower-third .headline::before,
.lower-third .subtitle::before {
	content: '';
	transform: skew(-18deg);
	position: absolute;
	top: 0;
	left: 0;
	right: 0;
	bottom: 0;
	z-index: -1;
}

.lower-third .headline::before {
	@apply bg-chocolate;
}

.headline:hover input,
.headline input:focus,
.subtitle:hover input,
.subtitle input:focus,
.copy:hover .text,
.copy textarea {
	outline: 2px dashed currentColor;
	outline-offset: 1px;
}

.headline input:not(:focus),
.subtitle input:not(:focus) {
	cursor: pointer;
}

.lower-third .headline input {
	font-size: 5em;
	height: 1.28em; /* 64px */
}

.lower-third .subtitle {
	margin: -.3em 0 6.5em;
	padding: .9em 0;
}

.lower-third.items-center .subtitle {
	padding-left: 5.2em;
	padding-right: 5.2em;
}

.lower-third .subtitle::before {
	@apply bg-peach;
}

.lower-third .subtitle input {
	font-size: 3.5em;
	height: 1.3428571em; /* 47px */
}
</style>
